name: quick_check

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:
  workflow_dispatch:

env:
  MEM_SIZE: 1073741824
  SCALE_FACTOR: 0.2

jobs:
  build_check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: tarantool/setup-tarantool@v4
        with:
          tarantool-version: '3.8'

      - name: Run micro bench (SF=0.2)
        shell: bash
        run: |
          make create_TNT_db SCALE_FACTOR=$SCALE_FACTOR MEM_SIZE=$MEM_SIZE
          make MEM_SIZE=$MEM_SIZE bench-tnt
